feat(theming): Add support for ExtendedFloatingActionButton (#67)
nextcloud/android-common pull request #68
Opened 2023-02-11 10:24 UTC by stefan-niedermann

# :eye:  Samples

Base | Light | Dark
--- | --- | ---
`#0082c9` (Nextcloud default brand) | ![image](https://user-images.githubusercontent.com/4741199/218252728-77142425-9215-43d0-8485-0a30de969515.png) | ![image](https://user-images.githubusercontent.com/4741199/218252709-669139ad-56ae-439f-a044-062982c9abf8.png)
`#bf678b` | ![image](https://user-images.githubusercontent.com/4741199/218252681-295788b4-4222-404a-ae02-c65d4b70d980.png) | ![image](https://user-images.githubusercontent.com/4741199/218252700-25c248be-3dee-4cdb-9af1-f51048400975.png)
`#a5b872` | ![image](https://user-images.githubusercontent.com/4741199/218252764-8999d566-16c6-4a50-97ce-05f6fbd5f4e6.png) | ![image](https://user-images.githubusercontent.com/4741199/218252776-3abd90fa-9581-4c41-9930-ab713c2d4cfc.png)
`#6ea68f` | ![image](https://user-images.githubusercontent.com/4741199/218252814-187fd063-ccb1-4739-93c7-1af8c9254e6c.png) | ![image](https://user-images.githubusercontent.com/4741199/218252802-837bbe0e-f78b-4d17-805b-af58140732ea.png)

2023-02-14 11:29 UTC, AndyScherzinger requested changes
The FAB's text will need to be colored according to the iconTint lint

2023-02-14 11:29 UTC, AndyScherzinger commented on ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/MaterialViewThemeUtils.kt
> +            )
The FAB's text will need to be colored according to the iconTint lint

2023-02-14 12:05 UTC, AndyScherzinger approved these changes
LGTM 👍 
Thanks for the near-real-time, instant fix 🎸

2023-02-15 13:49 UTC, AlvaroBrey approved these changes

2023-02-15 14:54 UTC, merged